import Head from 'next/head'
import Image from 'next/image'
import  excuteQuery from "../lib/db";
import {server} from '../config'
import styles from '../styles/Home.module.css'
import axios from 'axios'
export default function Home({data}) {

console.log('poss',data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>
  <h1>hello world</h1>
</div>



    </div>
  )
}



export async function getServerSideProps(context) {
   const res = await fetch(`${server}/api/system`);
   console.log('res',res)
   const data = await res.json();
   console.log('res------>',data)
 




  if (!res) {
    return {
      notFound: true
    };
  }

  return {
    props: { data }
  };
}






